name: mrna-pipeline
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - biopython
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - plotly
  - jinja2
  - pip
  - pip:
    - cutadapt
